//
// Created by Yifei Yang on 3/3/21.
//

#ifndef NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PLACEMENT_PLACEMENTSTRATEGY_H
#define NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PLACEMENT_PLACEMENTSTRATEGY_H

namespace normal::plan::placement {

enum PlacementStrategy {
  UNIFORM_HASH
};

}

#endif //NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PLACEMENT_PLACEMENTSTRATEGY_H
